### ISSUE TITLE
转弯时匹配情况较差，无法完成建图

### ISSUE THREAD

**Issue by xiaoxueshengyao** [BrenYi/Light-LOAM#1]
感谢您的工作，我用自己的数据集做了简单测试，不过每次都无法正常完成建图，如下所示，是需要对某些参数进行调整么，我用的16线的激光雷达
![lightloam](https://github.com/BrenYi/Light-LOAM/assets/33504360/677d754d-4f67-45b2-85d8-54cd83c4fd39)

**Comment by BrenYi** [comment]
感谢您对本工作的关注，个人觉得无法完成建图可能有两方面的原因，一是你这个在文件中雷达的线束以及相关配置没有设置正确。二是代码是默认未对点云的运动畸变进行补偿，注释了运动畸变校正部分的代码，您可能得加上去畸变模块代码。
